/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import static Main.Controller.getConnection;
import static Main.MenuWindow.MenuOpen;
import static Main.PopUp.PopUpWin;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rnavicka
 */
public class DeleteEmployee extends javax.swing.JFrame {

    /**
     * Creates new form DeleteEmployee
     */
    public DeleteEmployee() throws Exception {
        initComponents();
        DeleteEmployeeQr();
    }
    public void DeleteEmployeeQr() throws Exception{
        try{
            Connection con = getConnection();
            String sql = "SELECT * FROM employeelist";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            resultTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){String e1 = e.toString();
                    PopUpWin(e1);}
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DelPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        emplTable = new javax.swing.JTable();
        closebtn = new javax.swing.JLabel();
        closebtn1 = new javax.swing.JLabel();
        OverlayPanel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        BackBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DelPanel.setBackground(new java.awt.Color(32, 33, 35));
        DelPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        DelPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        DelPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resultTable.setBackground(new java.awt.Color(32, 33, 35));
        resultTable.setForeground(new java.awt.Color(0, 102, 153));
        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resultTable);

        emplTable.setBackground(new java.awt.Color(32, 33, 35));
        emplTable.setForeground(new java.awt.Color(0, 102, 153));
        emplTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(emplTable);

        closebtn.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        closebtn.setForeground(new java.awt.Color(0, 102, 153));
        closebtn.setText("X");
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });

        closebtn1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        closebtn1.setForeground(new java.awt.Color(0, 102, 153));
        closebtn1.setText("X");
        closebtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DelPanelLayout = new javax.swing.GroupLayout(DelPanel);
        DelPanel.setLayout(DelPanelLayout);
        DelPanelLayout.setHorizontalGroup(
            DelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DelPanelLayout.createSequentialGroup()
                        .addGroup(DelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DelPanelLayout.createSequentialGroup()
                        .addComponent(closebtn1)
                        .addGap(66, 66, 66)
                        .addComponent(closebtn)
                        .addContainerGap())))
            .addGroup(DelPanelLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DelPanelLayout.setVerticalGroup(
            DelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closebtn)
                    .addComponent(closebtn1))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        getContentPane().add(DelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 0, 724, -1));

        OverlayPanel.setBackground(new Color(0, 0, 0,200));
        OverlayPanel.setMaximumSize(new java.awt.Dimension(200, 600));
        OverlayPanel.setMinimumSize(new java.awt.Dimension(200, 600));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        OverlayPanel.setLayout(flowLayout1);

        jLayeredPane1.setAlignmentX(1.0F);
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(30, 30));

        BackBtn.setBackground(new java.awt.Color(32, 33, 35));
        BackBtn.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(0, 102, 153));
        BackBtn.setText("<");
        BackBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BackBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });

        jLayeredPane1.setLayer(BackBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BackBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BackBtn)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        OverlayPanel.add(jLayeredPane1);

        getContentPane().add(OverlayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 600));
        OverlayPanel.getAccessibleContext().setAccessibleParent(null);

        jLabel1.setBackground(new java.awt.Color(32, 33, 35));
        jLabel1.setForeground(new java.awt.Color(32, 33, 35));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/node.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resultTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultTableMouseClicked
        try {
            int column = 0;
            int row = resultTable.getSelectedRow();
            String value = resultTable.getModel().getValueAt(row, column).toString();
            Connection con = getConnection();
            String sqls = "SELECT * FROM employeelist WHERE empID = ('"+value+"')";
            PreparedStatement ps = con.prepareStatement(sqls);
            ResultSet rs = ps.executeQuery();
            emplTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            String e1 = ex.toString();
            PopUpWin(e1);
        }
    }//GEN-LAST:event_resultTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int column = 0;
            int row = 0;
            String value = emplTable.getModel().getValueAt(row, column).toString();
            System.out.println("The row is:" + value);
            Connection con = getConnection();
            String sqls = "DELETE FROM employeelist WHERE empID = ('"+value+"')";
            PreparedStatement ps = con.prepareStatement(sqls);
            int rs = ps.executeUpdate();
            DeleteEmployeeQr();
            DefaultTableModel emploTable = (DefaultTableModel) emplTable.getModel();
            emploTable.setRowCount(0);
        } catch (Exception ex) {
            String e1 = ex.toString();
            PopUpWin(e1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_closebtnMouseClicked

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        this.setVisible(false);
        MenuOpen();        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnMouseClicked

    private void closebtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtn1MouseClicked
        System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_closebtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void DelEmp() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DeleteEmployee().setVisible(true);
                } catch (Exception ex) {
                    String e1 = ex.toString();
                    PopUpWin(e1);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JPanel DelPanel;
    private javax.swing.JPanel OverlayPanel;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel closebtn1;
    private javax.swing.JTable emplTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable resultTable;
    // End of variables declaration//GEN-END:variables
}
